services:
  postgres:
    image: postgres:16
    container_name: yrkco_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Howard46
      POSTGRES_DB: yrkco_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
